version: '3.9'

networks:
  news:
    name: news
    external: true
  news-mongodb:
    name: news-mongodb
    external: false
  news-minio:
    name: news-minio
    external: true
  news-redis:
    name: news-redis
    external: true

volumes:
  mongo-data:
    name: mongo-data

services:
  mongodb:
    image: mongo:6.0.6
    container_name: news-mongodb-1
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - news-mongodb
  
  redis:
    restart: unless-stopped
  
  news-web:
    build:
      context: .
      dockerfile: Dockerfile
    image:
      ${IMAGE_NAME:-news-worker}:${TAG:-1.0}
    container_name: news-web-1
    environment:
      - ENV_FILE=.env
    restart: unless-stopped
    depends_on:
      - mongodb
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    command: bash -c "cd /usr/app && python -m uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - ${PORT_EXPOSED:-8000}:8000
    networks:
      - news
      - news-mongodb
      - news-minio
      - news-redis
